### ISSUE TITLE
Dataset not defined

### ISSUE THREAD

**Issue by soupslurpr** [Locutusque/TinyMistral-train-eval#1]
On the third code block I get Dataset not defined error when running it (running non multi gpu version) pls help :D

**Comment by Locutusque** [comment]
error code?

**Comment by Locutusque** [comment]
Actually I think I know what you're talking about I may have made a slight oversight

**Comment by Locutusque** [comment]
Tell me how that commit works for you

**Comment by soupslurpr** [comment]
Yep now its running

**Comment by soupslurpr** [comment]
I'm just running it on the default settings idk what I'm doing 😆

**Comment by Locutusque** [comment]
Okay! That's good to hear. I'll be closing this now.
